chore: update jwt payload, add lint-staged

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,36 +1,32 @@
 #!/usr/bin/env sh
 . "$(dirname -- "$0")/_/husky.sh"
 
-
-# Navigate to frontend, run linting and formatting
-echo "⏳ Running linting and formatting for frontend..."
-cd frontend && npm run lint:fix && npm run format || {
-  echo "❌ Frontend linting or formatting failed.";
+echo "⏳ Running linting and formatting for staged files..."
+# Run lint-staged to lint and format the files
+npx lint-staged || {
+  echo "❌ Linting or formatting failed. Please fix the issues before proceeding.";
   exit 1;
 }
-echo "✅ Frontend linting and formatting completed. ⏳ Trying to check Backend now...";
 
+echo "✅ Linting and formatting completed."
 
-# Navigate to backend, run linting and formatting
-cd ../backend && npm run lint:fix && npm run format || {
-  echo "❌ Backend linting or formatting failed.";
-  exit 1;
-}
-echo "✅ Backend linting and formatting completed.";
+# echo "⏳ Checking if linting/formatting modified any files..."
+# # Check if any files have been modified by lint-staged
+# git diff --cached --exit-code -- 'frontend/**/*.{ts,tsx}' 'backend/**/*.ts' || {
+#   echo "❌ Linting/formatting modified files. Please review the changes and re-add them before committing.";
+#   exit 1;
+# }
 
-# Return to the root directory
-cd ..
+# echo "✅ No unexpected changes detected."
 
-echo "✅ Alright! All checks are passed. ⏳ Trying to build now...";
-
+echo "⏳ Building the project..."
 # Build the project
-npm run build-all ||
-{
-  echo "❌ Your build failed, fix the errors above and try to commit again";
-  false;
+npm run build-all || {
+  echo "❌ Build failed. Please resolve the issues above and try committing again.";
+  exit 1;
 }
 
-echo "✅ Build completed!"
+echo "✅ Build completed successfully!"
 
-# If everything is okay
+# If everything is okay, exit with success
 exit 0
